### ISSUE TITLE
Getting an error -9949

### ISSUE THREAD

**Issue by AxelKohlepp** [miyako/4d-plugin-tesseract-v2#1]
I get the Error if i try the Democode ?!

Thank you in advance

Axel Kohlepp

**Comment by AxelKohlepp** [comment]
![Bildschirmfoto 2019-03-17 um 12 55 24](https://user-images.githubusercontent.com/22775620/54492937-281c1200-48cb-11e9-8675-11d9367edfdc.png)
![Bildschirmfoto 2019-03-17 um 12 56 06](https://user-images.githubusercontent.com/22775620/54492938-281c1200-48cb-11e9-9c75-49836fe51f54.png)
![Bildschirmfoto 2019-03-17 um 12 57 06](https://user-images.githubusercontent.com/22775620/54492939-281c1200-48cb-11e9-884d-7677905254d3.png)

**Comment by miyako** [comment]
this is expected. 
Xcode on Mojave only supports 10.13 and above.
I keep a copy of old Xcode for 32-bit and old Mac support, 
you can do the same and recompile the project using your old Mac.
that is the whole point of publishing the source code.

**Comment by AxelKohlepp** [comment]
Hello and sorry,

I don´t have many expieriences with XCode.

But on compiling for os x 10.11 i get the attached errors.

Thank you in advance

Axel Kohlepp
AxelKohlepp®2015

Keisuke Miyako schrieb:
