### ISSUE TITLE
Release 1.2.1

### ISSUE THREAD

**Issue by MatthieuLamp** [miyako/4d-plugin-tesseract-v2#3]
Hi

The release 1.2.1 does not work

**Comment by miyako** [comment]
could you be more specific?

1. what is the platform (OS version) ?
2. what exactly do you mean by "doesn't work" - plugin doesn't load, empty result, crash, freeze...

you may be surprised, but the plugin is working for me, and the user who requested the update.

so please do not assume that a short "doesn't work" comment is enough to fix your issue (because, I have no doubt that it is not working for you, but I can not help unless I know what condition makes it different for you)

**Comment by MatthieuLamp** [comment]
Dear Keisuke,

I apologize for not being enough precise in my comment. 
I only updated the new release without making any modification of the tessdata folder.
And the result is I do not obtain any text.
4D v18 / macOS 10.15.4 / fra
Thanks again for your support.

Best Regards,
Matthieu

**Comment by miyako** [comment]
it seems like ``1.2.1`` is linked to the wrong ``libjpeg``. I see that it does not process ``.jpeg`` files well. did you use a ``.jpeg`` file?

1.2.1

```json
{
   "SIM" : {
      "isAVX2Available" : true,
      "isAVX512BWAvailable" : false,
      "isAVX512FAvailable" : false,
      "isAVXAvailable" : true,
      "isSSEAvailable" : true
   },
   "leptonica" : "leptonica-1.80.0",
   "libraries" : "libjpeg Adobe : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 1.0.0",
   "version" : "4.1.1"
}
```

1.2

```json
{
   "SIM" : {
      "isAVX2Available" : true,
      "isAVX512BWAvailable" : false,
      "isAVX512FAvailable" : false,
      "isAVXAvailable" : true,
      "isSSEAvailable" : true
   },
   "leptonica" : "leptonica-1.78.0",
   "libraries" : "libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 2.0.0) : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 1.0.0",
   "version" : "4.1.0-rc1"
}
```

**Comment by MatthieuLamp** [comment]
Yes i used jpg ;-)

**Comment by tbuckler** [comment]
Sorry to report, but I am getting failures with JPG's as well. TIF's & PNG continue to work.

Both OSX10.15 and 10.14, with 4D v18 and 4D v16. Also tried OEM = 1, no change.

Tom


Tom Buckler | Buckler Microelectronics Inc.
17008 - 90 Avenue NW | Suite 272 | Edmonton | AB | Canada | T5T 1L6
Cell: (780) 499-5525

**Comment by miyako** [comment]
could you guys please give ``1.3.0`` a try?

Thanks!

**Comment by tbuckler** [comment]
So far so good. I'll run a few more tests this week, but it processed a few jpgs ok.

Thanks!


Tom Buckler | Buckler Microelectronics Inc.
17008 - 90 Avenue NW | Suite 272 | Edmonton | AB | Canada | T5T 1L6
Cell: (780) 499-5525

**Comment by MatthieuLamp** [comment]
it's ok for me !

Thanks Keisuke !
