### ISSUE TITLE
Version Info incorrect

### ISSUE THREAD

**Issue by joerg-eyring** [miyako/4d-plugin-tesseract-v2#5]
Hi Keisuke,
the file "InfoPlist.strings" within the folder "Resources" contains outdated information:

CFBundleShortVersionString = "2.0.0";
CFBundleGetInfoString = "Tesseract version 2.0.0, Copyright 2020 miyako.";

Shouldn't it read "2.1.0" and "Copyright 2020-2021 miyako." for example - as in the file "Info.plist"? Because of this the Finder still displays version "2.0.0" in the information window.

Regards, Jörg

**Comment by miyako** [comment]
should be ok in 2.1.0.0 release (named this way to avoid duplicate tag name)

**Comment by joerg-eyring** [comment]
Hi Keisuke,

thanks for the quick fix :-)
